### PR TITLE
fix issue with secret/prefix entries with no path

### LINKED ISSUE #165: (configuration) path is required if secret block is present
### Envconsul version
0.7.3 (daa2947)

### Configuration
```hcl
consul {
  address = "consul.service.consul:8500"

  ssl {
    enabled = false
  }

  retry {
    enabled = true
    attempts = 12
    backoff = "10s"
  }
}

max_stale = "10m"

exec {
  splay = "5s"
  kill_timeout = "5s"
}

vault {
  address = "http://vault.service.consul:8200"
  renew_token = false

  ssl {
    enabled = false
  }

  retry {
    enabled = true
    attempts = 12
    backoff = "10s"
  }
}

secret {
  no_prefix = true
  format = "DB_{{ key }}"
}

```
### Command
```shell
envconsul -secret="mongodb/creds/ptv_master" -config="deploy/envconsul.hcl" node .
```

### Expected behavior
As said in your changelog.md file, since version 0.7.0 `(configuration) path is deprecated and there is no configuration file replacement. Use the CLI option instead.`.

That's not true. Not specifying a path in the config file makes envconsul crash. You **must** still set it under `secret { path = "" }` to make it work.

### Actual behavior
~~~
2018/02/22 14:03:30.660697 looking at vault
2018/02/22 14:03:30.660731 [ERR] (cli) vault.read: invalid format: ""
~~~

### Steps to reproduce
1. Create a consul config file **without the path** specified in `secret`.
2. Run envconsul specifying the proper secret via `-secret`
3. Enjoy

PS. I'm creating this issue after (accidentally) upgrading from 0.6.2 to the latest version. Even with the specified changes, envconsul is not able to connect to vault. It always returns a `renewed returned` error... That's why I'm trying to make all the changes as specified in changelog, but as stated it does not work.

PS2. Please, update the config file in the readme. It does not reflect all these changes.

### PR DESCRIPTION
**Pull request by eikenb**
Issue came up when user had a secret config section with no path set (but had noprefix) and where setting the path on the cli. The documentation on how this was handled was unclear so the user thought it was a bug.

I fixed the issue so that their test would have worked by filtering out the secret config entry with no path (as the path is required).

I also updated the documentation to help clarify how prefix and secret (they use the same code) work.

Fixes #165

### CODE REVIEW

File: config_test.go [hunk 1]
```diff
@@ -1221,6 +1221,10 @@ func TestParse(t *testing.T) {
 			if !reflect.DeepEqual(tc.e, c) {
 				t.Errorf("\nexp: %#v\nact: %#v", tc.e, c)
 			}
+			// should test but at least run to catch big errors
```
Comment (lornasong) [inline config_test.go:1224]: does "catch big errors" mean that by running `Finalize()` it'll at least catch something like a panic?
